kind: Service
apiVersion: v1
metadata:
    name: kong-db
spec:
    selector:
        app: kong-db
    ports:
        - protocol: "TCP"
          port: 5432
          targetPort: kong-db

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kong-db
        track: stable
    spec:
      containers:
        - name: kong-db
          image: "postgres:9.4"
          env:
            - name: POSTGRES_USER
              value: 'kong'
            - name: POSTGRES_PASSWORD
              value: 'kong'
            - name: POSTGRES_DB
              value: 'kong'
          ports:
            - name: kong-db
              containerPort: 5432
