apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cal-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cal-db
        track: stable
    spec:
      containers:
        - name: cal-db
          image: "postgres:alpine"
          env:
            - name: POSTGRES_USER
              value: 'lpraat'
            - name: POSTGRES_PASSWORD
              value: 'password'
          ports:
            - name: cal-db
              containerPort: 5432
