kind: Service
apiVersion: v1
metadata:
    name: cal
spec:
    selector:
        app: cal
    ports:
        - protocol: 'TCP'
          port: 80
          targetPort: cal-uwsgi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cal
        track: stable
    spec:
      containers:
        - name: cal
          image: "lpraat/calendarservice:latest"
          env:
            - name: DB_USER
              value: 'lpraat'
            - name: DB_PASSWORD
              value: 'password'
            - name: DB_IP
              value: cal-db.default.svc.cluster.local
            - name: DB_DB
              value: 'lpraat'
            - name: DB_PORT
              value: '5432'
            - name: EVENT_STORE_USER
              value: 'lpraat'
            - name: EVENT_STORE_PASSWORD
              value: 'password'
            - name: EVENT_STORE_IP
              value: cal-es.default.svc.cluster.local
            - name: EVENT_STORE_DB
              value: 'lpraat'
            - name: EVENT_STORE_PORT
              value: '5432'
            - name: RABBITMQ_IP
              value: rabbit.default.svc.cluster.local
            - name: RABBITMQ_PORT
              value: '5672'
          ports:
            - name: cal-uwsgi
              containerPort: 8003
