kind: Service
apiVersion: v1
metadata:
    name: acc
spec:
    selector:
        app: acc
    ports:
        - protocol: "TCP"
          port: 80
          targetPort: acc-uwsgi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: acc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: acc
        track: stable
    spec:
      containers:
        - name: acc
          image: "lpraat/accountservice:latest"
          env:
            - name: DB_USER
              value: 'lpraat'
            - name: DB_PASSWORD
              value: 'password'
            - name: DB_IP
              value: acc-db.default.svc.cluster.local
            - name: DB_DB
              value: 'lpraat'
            - name: DB_PORT
              value: '5432'
            - name: EVENT_STORE_USER
              value: 'lpraat'
            - name: EVENT_STORE_PASSWORD
              value: 'password'
            - name: EVENT_STORE_IP
              value: acc-es.default.svc.cluster.local
            - name: EVENT_STORE_DB
              value: 'lpraat'
            - name: EVENT_STORE_PORT
              value: '5432'
            - name: RABBITMQ_IP
              value: rabbit.default.svc.cluster.local
            - name: RABBITMQ_PORT
              value: '5672'
            - name: KONG_IP

          ports:
            - name: acc-uwsgi
              containerPort: 8002
