kind: Service
apiVersion: v1
metadata:
    name: rabbit
spec:
    selector:
        app: rabbit
    ports:
        - protocol: "TCP"
          port: 5672
          targetPort: rabbit

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbit
        track: stable
    spec:
      containers:
        - name: rabbit
          image: "rabbitmq:3"
          ports:
            - name: rabbit
              containerPort: 5672
