apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ev
        track: stable
    spec:
      containers:
        - name: ev
          image: "lpraat/eventservice:latest"
          env:
            - name: DB_USER
              value: 'lpraat'
            - name: DB_PASSWORD
              value: 'password'
            - name: DB_IP
              value: ev-db.default.svc.cluster.local
            - name: DB_DB
              value: 'lpraat'
            - name: DB_PORT
              value: '5432'
            - name: EVENT_STORE_USER
              value: 'lpraat'
            - name: EVENT_STORE_PASSWORD
              value: 'password'
            - name: EVENT_STORE_IP
              value: ev-es.default.svc.cluster.local
            - name: EVENT_STORE_DB
              value: 'lpraat'
            - name: EVENT_STORE_PORT
              value: '5432'
            - name: RABBITMQ_IP
              value: rabbit.default.svc.cluster.local
            - name: RABBITMQ_PORT
              value: '5672'
          ports:
            - name: ev-uwsgi
              containerPort: 8004
