apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbit
        track: stable
    spec:
      containers:
        - name: rabbit
          image: "rabbitmq:3"
          ports:
            - name: rabbit_port
              containerPort: 5672
