kind: Service
apiVersion: v1
metadata:
    name: com-redis
spec:
    selector:
        app: com-redis
    ports:
        - protocol: "TCP"
          port: 6379
          targetPort: com-redis

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: com-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: com-redis
        track: stable
    spec:
      containers:
        - name: com-redis
          image: redis
          ports:
            - name: com-redis
              containerPort: 6379

