kind: Service
apiVersion: v1
metadata:
    name: accountservice_db
spec:
    selector:
        app: accountservice_db
    ports:
        - protocol: "TCP"
          port: 5432
          targetPort: accountservice_db_port
